# Generated by Django 3.2.16 on 2023-08-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20230821_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='networth',
            field=models.BigIntegerField(default=0),
        ),
    ]
