# Generated by Django 3.2.16 on 2023-08-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_deposit_networth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='created',
        ),
    ]
