# Generated by Django 3.2.16 on 2023-08-27 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_deposit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 12, 54, 45, 556669, tzinfo=utc)),
        ),
    ]
