# Generated by Django 3.2.16 on 2023-08-27 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_deposit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 13, 15, 16, 210890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 13, 15, 16, 199341, tzinfo=utc)),
        ),
    ]
