# Generated by Django 3.2.16 on 2023-08-27 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20230827_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 13, 33, 30, 382558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 13, 33, 30, 368585, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 13, 33, 30, 383431, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(default='successful', max_length=200),
        ),
    ]
