# Generated by Django 3.2.16 on 2023-08-30 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20230827_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='networth',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.banktransaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 13, 36, 28, 228842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 13, 36, 28, 241258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
